-- 添加头像字段到客户表和教练表

-- 为客户表添加头像字段
ALTER TABLE tb_customer ADD COLUMN avatar TEXT DEFAULT NULL COMMENT '客户头像';

-- 为教练表添加头像字段
ALTER TABLE tb_coach ADD COLUMN avatar TEXT DEFAULT NULL COMMENT '教练头像';

-- 显示修改结果
SELECT '头像字段添加完成！' AS result;
SELECT '客户表结构：', COLUMN_NAME, DATA_TYPE, COLUMN_COMMENT FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'tb_customer' AND COLUMN_NAME = 'avatar';
SELECT '教练表结构：', COLUMN_NAME, DATA_TYPE, COLUMN_COMMENT FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'tb_coach' AND COLUMN_NAME = 'avatar';